### ISSUE TITLE
Initialization within context

### ISSUE THREAD

**Issue by macmpi** [JedS/Raspdac#1]
Hi,

While I'm trying to do some fixes in Volumio plugin management, I'm looking around at existing plugins to check about potentially conflicting issues.

I noticed Raspdac is not returning promises in onVolumioStart() and onStop().
Since plugin management rely on this for queuing operations across plugins, not using promises will most probably produce erratic behaviors, and potential crashes with upcoming changes.
You may want to consider using such promises so that plugin is more future-proof.

Also, for interrop with other plugins using GPIOs, it may be preferable to create GPIOs, set watch functions within onStart() (rather than in context), and destroy in onStop().
This would allow to free those resources for others when the plugin is not actually used.

Thanks for consideration.

**Comment by JedS** [comment]
Done
Can you review the modification and eventually close this issue ?

**Comment by macmpi** [comment]
That was quick, great!
