### ISSUE TITLE
Fonctionnement Bouton

### ISSUE THREAD

**Issue by ManuCpam** [JedS/Raspdac#3]
Bonjour,

J'ai dernièrement acheté un PI3+DAC AudioPhonics I-Sabre V3+ Bouton poussoir monostable. Après installation de la dernière version de l'image Volumio ( V2.175 du 16-05-2017) sur le PI, j'ai installé le plugin pour gérer le bouton et l'allumage/extinction de l'ensemble.
Je n'ai pas d'afficheur. Le bouton ne semble pas fonctionner (allumage led fixe/ démarre avec une pression, mais pas d'arrêt). Que vérifier sur le système pour être sur que tout est correctement installé pour la gestion du Bouton ? 
Merci pour votre retour
Cdtl

**Comment by JedS** [comment]
Bonjour,
Sans la gestion du bouton, la led n'arrete pas de clignoter.
Si elle reste au fixe, c'est que cela fonctionne. Pour arreter le RaspDac, il faut laisser appuyer sur le bouton power. De memoire, une seule pression permet de faire un reset du dac (a confirmer).
Pour ce qui est de l'affichage, il n'est present que lorsque le dac joue un morceau.

Cordialement,

**Comment by ManuCpam** [comment]
Bonjour,
Merci pour votre réponse. Après vérification du cablage du bouton, j'avais fait une erreur :-(  . Une fois câblé correctement tout est OK. C'est ça de vouloir aller trop vite. Quand je disais 'je n'ai pas d'afficheur', je voulais dire que je ne l'ai pas commandé, donc pas branché.
Merci pour votre travail.
Cdtl
