### ISSUE TITLE
Not suitable for I2C display

### ISSUE THREAD

**Issue by FedorMil** [JedS/Raspdac#6]
Hey. Tell me how to edit your code to work with the I2C display. When I install the plugin, I do not open any properties and nothing is displayed on the screen.

**Comment by JedS** [comment]
Hi,
I guess you'll have to :
- use a I2C node js module ( https://www.npmjs.com/search?q=i2c)
- rewrite a new raspdacDisplay for your I2C display. The current raspdacDisplay is notify when something change on Volumio via the pushState method.
